### ISSUE TITLE
rpc not returning error reason

### ISSUE THREAD

**Issue by SurfingNerd** [DMDcoin/openethereum-3.x#138]
Raw result of a transaction execution made with web3
However, the RPC Node knows the Error, Blockscout can retrieve it using the trace API.

On Hardhat tests, hardhat do not even send transactions that will result in an error,
and always returns: "ProviderError: The execution failed due to an exception"

This makes tests like this impossible - it's only possible against the "hardhat" network ?!

```
  it("minting should fail if not registered", async () => {
    if (nft) {
      await expect(nft.mintTo(main)).to.be.revertedWith("minting not registered");
    }
  });
```
results in:
```
  1) NFT
       minting should fail if not registered:
     AssertionError: Expected transaction to be reverted with minting not registered, but other exception was thrown: ProviderError: The execution failed due to an exception.
 ```

Here is a transaction that was sent manually (since hardhat seem not to send transactions when the call already returns an exception)

http://explorer.uniq.diamonds/tx/0x9d4b6be8adb1bf0a09c7fbf1627bd330c8dbf5559649ffeef1ddcba7524b06d1/internal-transactions

```
{
  "blockHash": "0xce3916df7680104a4480737ceb5ebba912771b950fa5c227e90be75a3cc2ad8d",
  "blockNumber": 292576,
  "contractAddress": null,
  "cumulativeGasUsed": 29550,
  "effectiveGasPrice": 1000000000,
  "from": "0xf9288606c96e1b9cabe29b4f94672d4497409f50",
  "gasUsed": 29550,
  "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  "status": false,
  "to": "0xbd309a2027a24d02db251acce5160ddd2e2d5f62",
  "transactionHash": "0x9d4b6be8adb1bf0a09c7fbf1627bd330c8dbf5559649ffeef1ddcba7524b06d1",
  "transactionIndex": 0,
  "type": "0x0",
  "events": {}
}
    at Object.TransactionError (web3.min.js:18558:1)
    at Object.TransactionRevertedWithoutReasonError (web3.min.js:18568:1)
    at web3.min.js:4102:1
    at h (web3.min.js:25354:1)
    at Generator._invoke (web3.min.js:25337:1)
    at Generator.next (web3.min.js:25379:1)
    at n (web3.min.js:7478:1)
    at s (web3.min.js:7492:1)
    at web3.min.js:7497:1
    at new Promise (<anonymous>)
TransactionError @ web3.min.js:18558
TransactionRevertedWithoutReasonError @ web3.min.js:18568
(anonymous) @ web3.min.js:4102
h @ web3.min.js:25354
(anonymous) @ web3.min.js:25337
(anonymous) @ web3.min.js:25379
n @ web3.min.js:7478
s @ web3.min.js:7492
(anonymous) @ web3.min.js:7497
(anonymous) @ web3.min.js:7489
(anonymous) @ web3.min.js:4117
setTimeout (async)
_fireError @ web3.min.js:2432
(anonymous) @ web3.min.js:4102
h @ web3.min.js:25354
(anonymous) @ web3.min.js:25337
(anonymous) @ web3.min.js:25379
n @ web3.min.js:7478
s @ web3.min.js:7492
(anonymous) @ web3.min.js:7497
(anonymous) @ web3.min.js:7489
(anonymous) @ web3.min.js:4117
Promise.then (async)
x @ web3.min.js:4051
setInterval (async)
r @ web3.min.js:4130
(anonymous) @ web3.min.js:4132
(anonymous) @ web3.min.js:4141
Promise.then (async)
v._confirmTransaction @ web3.min.js:4140
a @ web3.min.js:4213
(anonymous) @ web3.min.js:18493
(anonymous) @ web3.min.js:23129
Promise.then (async)
(anonymous) @ web3.min.js:23128
Promise.then (async)
a.send @ web3.min.js:23127
c.send @ web3.min.js:18455
s @ web3.min.js:4220
Promise.then (async)
c @ web3.min.js:4226
n @ web3.min.js:4250
y._executeMethod @ web3.min.js:14103
onClick @ App.tsx:31
callCallback @ react-dom.development.js:3733
invokeGuardedCallbackDev @ react-dom.development.js:3777
invokeGuardedCallback @ react-dom.development.js:3834
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:3848
executeDispatch @ react-dom.development.js:7992
processDispatchQueueItemsInOrder @ react-dom.development.js:8018
processDispatchQueue @ react-dom.development.js:8029
dispatchEventsForPlugins @ react-dom.development.js:8038
(anonymous) @ react-dom.development.js:8198
batchedUpdates$1 @ react-dom.development.js:22595
batchedUpdates @ react-dom.development.js:3581
dispatchEventForPluginEventSystem @ react-dom.development.js:8197
dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay @ react-dom.development.js:5703
dispatchEvent @ react-dom.development.js:5697
dispatchDiscreteEvent @ react-dom.development.js:5674
```

**Comment by SurfingNerd** [comment]
closing error from alpha network
